# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Docstrap Documentation
email: osmarreyesst@gmai.com
description: >- # this means to ignore newlines until "baseurl:"
  Docstrap is an open-source library, allows you to generate documentation web-view for your projects in a organize and lightweight way
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
benefits: >-
  <div class="porperty">
  <i class="fas fa-feather-alt"></i>
  <h3>Lightweight</h3>
  <p>
  Docstrap scales well without adding overhead to the application. Generated files ara Plain vanilla HMTL-CSS-JS.
  </p>
  </div>
  <div class="porperty">
  <i class="fas fa-tachometer-alt"></i>
  <h3>Fast</h3>
  <p>
  Docstrap use NodeJS alone, avoiding convoluted frameworks so your documentation can be generated by yourself or CI/CD process in an optimal way.
  </p>
  </div>
links: >-
  <a href="#expressif">
  <img src="assets/img/expressif-boxmodel.jpeg" alt="expressif logo">
  </a>
  <a href="#metaflux">
  <img src="assets/img/metaflux-logo-black.svg" alt="metaflux logo">
  </a>
name: Docstrap
repository: https://github.com/rebelstackio/docstrap
discord: https://discord.gg/pRG332
stackoverflow: \#linkto-so
themecolor: default
clearlogo: assets/img/default-logo-white.svg
darklogo: assets/img/default-logo.svg

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
